<?php $this->headScript()->appendFile('') ?> 

<section class="content">
 
    <div class="row">
 
        <div class="col-md-12">
 
            <div class="box">
 
                <div class="box-header with-border">
 
                    <h3 class="box-title">Servicios</h3>
 
                    <div class="pull-right">
 
                    </div>

                    <div class="box-body">

                        <div class="table-toolbar">
                    
                            <div class="pull-left" style="padding: 1%">
                    
                                <a class="btn-small green darken-2" href="/catalogo/getinfo?optReg=set" data-toggle="tooltip" data-placement="bottom" data-original-title="Agregar"><i class="fa fa-plus"></i> Agregar Servicio</a>
                    
                            </div> 

                            <div class="pull-left" style="padding: 1%">
                    
                                <a class="btn-small green darken-2" href="/alcances/?optReg=set" data-toggle="tooltip" data-placement="bottom" data-original-title="Agregar"><i class="fa fa-plus"></i> Agregar Alcances</a>
                    
                            </div>                
                    
                        </div> 

                        <table  class="table text-left table-hover">
                    
                            <thead> 
                    
                                <tr role="row">                                                       

                                    <th>Nombre Catalogo</th>

                                    <th>Estatus</th>                                   
                                    
                                    <th></th>                                   
                                    
                                    <th></th>                                   
                    
                                </tr>                                
                    
                            </thead>                     
                    
                            <tbody>        
                    
                                <?php if(count($this->aData)>0):?> 
                    
                                    <?php foreach($this->aData as $k => $v): ?>  

                                        <tr class="odd gradeX">                                    

                                            <td><?php print $v['NOMBRE'];  ?></td>

                                            <td><?php print $v['ACTIVO'];  ?></td>
                    
                                            <td class="right-align">

                                               <?php if( $v['ACTIVO'] == 'ACTIVO'):?>

                                                    <a class="btn-small green darken-2" href="/producto/?catId=<?php echo $v['ID_TIPO'];?>&producto=<?php echo $v['NOMBRE'];?>"><i class="fa fa-server"></i> Administrar Servicio</a>
                                               
                                               <?php endif;?> 

                                            </td>   

                                            <td class="center-align">  

                                               <a href="/catalogo/upcatalogo?catId=<?php echo $v['ID_TIPO'];?>&optReg=up"><i class="fa fa-2x fa-edit"></i></a>

                                            </td>   

                                            <td class="center-align">

                                               <a class="delete" href="/catalogo/delete?catId=<?php echo $v['ID_TIPO'];?>&optReg=up" ><span class="warning"><i class="fa fa-2x fa-trash" style="color: red"></i></span></a>
 
                                            </td>

                                        </tr>   

                                    <?php endforeach;?>

                                <?php endif;?>

                            </tbody>

                        </table>

                    </div> 

                </div>

            </div>        

        </div>

    </div>

</section>

<?php if( $_GET['del'] == 1 ):?>

    <script>

       $(document).ready( function(){
          
          success();
       
       });

    </script>

<?php elseif ( $_GET['del'] == -1):?>

    <script>

       $(document).ready( function(){
          
          danger();
       
       });

    </script>

<?php endif; ?>


<script type="text/javascript">
    
    function success(){

        swal({

            icon: "success",

            text: "Se elimino de manera Correcta",

        });

    }

    function danger(){

        swal({

            icon: "error",

            text: "Ocurrio un error al eliminar",

        });

    }
    
</script>


<!--

    butonones agregar -- green darken-2

    editar --  light-blue darken-2

    eliminar .-- deep-orange darken-4



    -->