<?php $this->headScript()->appendFile('') ?> 

<section class="content">
 
    <div class="row">
 
        <div class="col-md-12">
 
            <div class="box">
 
                <div class="box-header with-border">
 
                    <h3 class="box-title">Productos</h3>
 
                    <div class="pull-right">
 
                    </div>

                    <div class="box-body">

                        <div class="table-toolbar">
                    
                            <div class="pull-left" style="padding: 1%">
                    
                                <a class="btn btn-sm icon-only  tooltip-success" href="/catalogo/getinfo?optReg=set" data-toggle="tooltip" data-placement="bottom" data-original-title="Agregar"><i class="fa fa-fw fa-plus-circle"></i> Agregar Catalogo</a>
                    
                            </div>                
                    
                        </div> 

                        <table  class="table table-bordered table-hover table-bordered">
                    
                            <thead> 
                    
                                <tr role="row">                                                       

                                    <th>Nombre Catalogo</th>

                                    <th></th>                                   
                    
                                </tr>                                
                    
                            </thead>                     
                    
                            <tbody>        
                    
                                <?php if(count($this->aData)>0):?> 
                    
                                    <?php foreach($this->aData as $k => $v): ?>  

                                        <tr class="odd gradeX">                                    

                                            <td><?php print $v['NOMBRE'];  ?></td>
                    
                                            <td>
 
                                               <a class="btn  btn-sm icon-only  tooltip-info" href="/catalogo/getinfo?catId=<?php echo $v['ID_SERVICIO'];?>" data-toggle="tooltip" data-placement="top" data-original-title="Editar"><i class="fa fa-edit"></i>Agregar Productos</a>

                                               <a class="btn  btn-sm icon-only  tooltip-info" href="/catalogo/getinfo?catId=<?php echo $v['ID_TIPO'];?>&optReg=up" data-toggle="tooltip" data-placement="top" data-original-title="Editar"><i class="fa fa-edit"></i>Editar Catalogo</a>
 
                                            </td>

                                        </tr>   

                                    <?php endforeach;?>

                                <?php endif;?>

                            </tbody>

                        </table>

                    </div> 

                </div>

            </div>        

        </div>

    </div>

</section>