
<div class="row">
    <div class="col m12 s12 text-center" style="margin-top: 20px;">
      <span class="title_view">Cotizaciones</span>
    </div>
</div>


<div class="row">
	<div class="col m12 s12">
		<div class="progress">
			<div class="circle "> 
				<span class="label">1</span>
				<span class="title">Subestaciones</span>
			</div> <span class="bar active"></span>

			<div class="circle" > 
				<span class="label">2</span>
				<span class="title">Transformadores</span>
			</div> <span class="bar"></span>

			<div class="circle"> 
				<span class="label">3</span>
				<span class="title">Tableros</span>
			</div><span class="bar"></span>

			<div class="circle"> 
				<span class="label">4</span>
				<span class="title">Banco de Cap</span>
			</div><span class="bar"></span>

			<div class="circle"> 
				<span class="label">5</span>
				<span class="title">Pruebas</span>
			</div>
		</div>
	</div>
</div>


<div class="row">
	<div class="col m12 s12">
		<div class="row">
			<div class="col m6 s6">
				<span class="subtitle_view">Cotizaciones Pendientes</span>
			</div>

			<div class="col m6 s6 text-right">
				<a class="btn" href="/cotizacion/crearcotizacion">Crear cotización</a>
			</div>
		</div>
		

    	<table>
        	<thead>
          		<tr>
              		<th>Id</th>
              		<th>Fecha Cotización</th>
              		<th>Personal</th>
              		<th>Paso</th>
              		<th></th>
          		</tr>
        	</thead>

        	<tbody>
          		<tr>
            		<td>1</td>
            		<td>14/02/2021</td>
            		<td>Fernando Herrera</td>
            		<td>Paso 1</td>
					<td>
						<a href="/panel/usuariodetail/id/1"><i class="fa fa-2x fa-id-card-o"></i></a>	
					</td>
					<td>
						<a class="delete" href="/panel/requestdeletealluser/id/1" ><span class="warning"><i class="fa fa-2x fa-trash" style="color: red"></i></span></a>
					</td>
          		</tr>
        	</tbody>
      	</table>
	</div>
</div>
