<div class="row">
    <div class="col m12 s12 text-center" style="margin-top: 10px;">
    	<span class="title_view">Transformadores</span>
    </div>
</div>

<div class="row">
	<div class="col m12 s12">
		<div class="progress">
			<div class="circle done"> 
				<span class="label">1</span>
				<span class="title">Subestaciones</span>
			</div> <span class="bar active"></span>

			<div class="circle done"> 
				<span class="label">2</span>
				<span class="title">Transformadores</span>
			</div> <span class="bar active"></span>

			<div class="circle"> 
				<span class="label">3</span>
				<span class="title">Tableros</span>
			</div><span class="bar"></span>

			<div class="circle"> 
				<span class="label">4</span>
				<span class="title">Banco de Cap</span>
			</div><span class="bar"></span>

			<div class="circle"> 
				<span class="label">5</span>
				<span class="title">Pruebas</span>
			</div>
		</div>
	</div>
</div>

<div class="row">
    <div class="col s12 m12">
      	<div class="card">
        	<div class="card-content">
          		<div class="row">
          			<div class="col m6 s6">
          				<span class="subtitle_view">Transformadores</span>
          			</div>
          			<div class="col m6 s6 text-right" id="subestacion_pendiente">
      						<div class="chip">
      						   	<img src="/img/gris.jpg" >
      						   	Pendiente
      						</div>
          			</div>
          			<div class="col m6 s6 oculto text-right" id="subestacion_seleccionada">
      						<div class="chip">
      						   	<img src="/img/correct.png" >
      						   	Seleciconada
      						</div>
          			</div>
          		</div>
          		<div class="row">
          			<div class="col m12 s12" style="margin-top: 10px;">
          				<?php foreach ($this->transformadores as $key){ ?>
						    <p>
						      <label>
						        <input name="subestaciones" class="subestcion_op" data-id="<?php echo $key['ID_TRANSFORMADOR']; ?>" data-descripcion="<?php echo $key['DESCRIPCION']; ?>" type="radio"/>
						        <span>Tipo: <?php echo $key['DESCRIPCION']; ?>, Capacidad: <?php echo $key['CAPACIDAD_KVA']; ?>, Tension: <?php echo $key['TENSION']; ?></span>
						      </label>
						    </p>
          				<?php } ?>
          			</div>
          		</div> 
        	</div>
      	</div>
    </div>
    <!-- E N D   S E C C I O N   T R A N S F O R M A D O R E S -->
</div>