
<div class="row" style="margin-top: 10px;">
    <div class="col m12 s12">
        <a href="/cotizacion/cotizaciones" class="grey lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>    
    </div>
</div>

<div class="row">
    <div class="col m12 s12 text-center" style="margin-top: 10px;">
    	<span class="title_view">Subestaciones</span>
    </div>
</div>

<div class="row">
	<div class="col m12 s12">
		<div class="progress">
			<div class="circle done"> 
				<span class="label">1</span>
				<span class="title">Subestaciones</span>
			</div> <span class="bar active"></span>

			<div class="circle" > 
				<span class="label">2</span>
				<span class="title">Transformadores</span>
			</div> <span class="bar"></span>

			<div class="circle"> 
				<span class="label">3</span>
				<span class="title">Tableros</span>
			</div><span class="bar"></span>

			<div class="circle"> 
				<span class="label">4</span>
				<span class="title">Banco de Cap</span>
			</div><span class="bar"></span>

			<div class="circle"> 
				<span class="label">5</span>
				<span class="title">Pruebas</span>
			</div>
		</div>
	</div>
</div>


<div class="row">
	<!--   S E C C I O N   S U B E S T A C I O N E S -->
    <div class="col s12 m12">
      	<div class="card">
        	<div class="card-content">
          		<div class="row">
          			<div class="col m6 s6">
          				<span class="subtitle_view">Subestaciones</span>
          			</div>
          			<div class="col m6 s6 text-right" id="subestacion_pendiente">
      						<div class="chip">
      						   	<img src="/img/gris.jpg" >
      						   	Pendiente
      						</div>
          			</div>
          			<div class="col m6 s6 oculto text-right" id="subestacion_seleccionada">
      						<div class="chip">
      						   	<img src="/img/correct.png" >
      						   	Seleciconada
      						</div>
          			</div>
          		</div>
          		<div class="row">
          			<div class="col m12 s12" style="margin-top: 10px;">
          				<?php foreach ($this->subestaciones as $key){ ?>
						    <p>
						      <label>
						        <input name="subestaciones" class="subestcion_op" data-id="<?php echo $key['ID_SUBESTACION']; ?>" data-descripcion="<?php echo $key['DESCRIPCION']; ?>" type="radio"/>
						        <span><?php echo $key['DESCRIPCION']; ?></span>
						      </label>
						    </p>
          				<?php } ?>
          			</div>
          		</div> 
        	</div>
      	</div>
    </div>
    <!-- E N D   S E C C I O N   S U B E S T A C I O N E S -->

    <!--   S E C C I O N   A L C A N C E S-->
    <div class="col s12 m12">
      	<div class="card">
        	<div class="card-content">
          		<div class="row">
          			<div class="col m6 s6">
          				<span class="subtitle_view">Alcances</span>
          			</div>
          			<div class="col m6 s6 text-right" id="alcance_pendiente">
						<div class="chip">
						   	<img src="/img/gris.jpg" >
						   	Pendiente
						</div>
          			</div>
          			<div class="col m6 s6 text-right oculto" id="alcance_seleccionada">
						<div class="chip">
						   	<img src="/img/correct.png" >
						   	Seleciconada
						</div>
          			</div>
          		</div>
          		<div class="row">
          			<div class="col m12 s12" style="margin-top: 10px;">
          				<?php foreach ($this->subestaciones_alcances as $key){ ?>
						    <p>
						      <label>
						        <input name="group1" class="alcance_op" data-id="<?php echo $key['ID_ALCANCE']; ?>" data-descripcion="<?php echo $key['DESCRIPCION']; ?>" type="radio"/>
						        <span><?php echo $key['DESCRIPCION']; ?></span>
						      </label>
						    </p>
          				<?php } ?>
          			</div>
          		</div> 
        	</div>
      	</div>
    </div>
    <!--  E N D  S E C C I O N   A L C A N C E S-->


    <!--  S E C C I O N   P R U E B A S-->
    <div class="col s12 m12">
      	<div class="card">
        	<div class="card-content">
          		<div class="row">
          			<div class="col m6 s6">
          				<span class="subtitle_view">Pruebas</span>
          			</div>

          			<div class="col m6 s6 text-right" id="pruebas_pendiente">
						<div class="chip">
						   	<img src="/img/gris.jpg" >
						   	Pendiente
						</div>
          			</div>
          			<div class="col m6 s6 text-right oculto" id="pruebas_seleccionada">
						<div class="chip">
						   	<img src="/img/correct.png" >
						   	Seleciconada
						</div>
          			</div>
          		</div>

          		<div class="row">
          			<div class="col m12 s12" style="margin-top: 10px;">
          				<?php foreach ($this->pruebas as $key){ ?>
						    <p>
						      <label>
						        <input name="pruebas" class="prueba_op" data-id="<?php echo $key['ID_PRUEBA']; ?>" data-prueba="<?php echo $key['PRUEBA']; ?>" data-descripcion="<?php echo $key['DESCRIPCION']; ?>" type="radio"/>
						        <span><?php echo $key['PRUEBA']; ?>: <?php echo $key['DESCRIPCION']; ?></span>
						      </label>
						    </p>
          				<?php } ?>
          			</div>
          		</div> 

        	</div>
      	</div>
    </div>
     <!-- E N D   S E C C I O N   P R U E B A S-->


    <!--   S E C C I O N E S-->
    <div class="col s12 m12">
      <div class="card">
        <div class="card-content">
          <span class="subtitle_view">Secciones</span>
          <div class="row" style="margin-top: 20px;">
            <div class="col s12 m4">
              <div class="card">
                <div class="card-content">
                  <div class="row">
                    <div class="col m8 s6">
                      <h4>Sección 1</h4>
                    </div>
                    <div class="col m4 s6">
                      <p>
                        <label>
                          <input name="secc" type="radio" />
                          <span></span>
                        </label>
                      </p>                     
                    </div>
                  </div>
                 
                  <div class="row"> 
                    <div class="col m12 s12 text-center">
                      <h4>PRECIO: $6,400</h4>
                    </div>
                    <div class="col m12 s12">
                    <table>
                      <thead>
                        <tr>
                          <th></th>
                        </tr>
                      </thead>

                      <tbody>
                        <tr>
                          <td>Una sección de medición</td>
                        </tr>
                        <tr>
                          <td>Una sección de cuchilla de servicio</td>
                        </tr>
                        <tr>
                          <td>Una sección de interruptor</td>
                        </tr>
                      </tbody>
                    </table>
                    </div>
                  </div>

                </div>
              </div>
            </div>  


            <div class="col s12 m4">
              <div class="card">
                <div class="card-content">
                  <div class="row">
                    <div class="col m8 s6">
                      <h4>Sección 2</h4>
                    </div>
                    <div class="col m4 s6">
                      <p>
                        <label>
                          <input name="secc" type="radio" />
                          <span></span>
                        </label>
                      </p>                     
                    </div>
                  </div>
                 
                  <div class="row"> 
                    <div class="col m12 s12 text-center">
                      <h4>PRECIO: $8,200</h4>
                    </div>
                    <div class="col m12 s12">
                    <table>
                      <thead>
                        <tr>
                          <th></th>
                        </tr>
                      </thead>

                      <tbody>
                        <tr>
                          <td>Una sección de medición</td>
                        </tr>
                        <tr>
                          <td>Una sección de cuchilla de servicio</td>
                        </tr>
                        <tr>
                          <td>Dos secciones de interruptor</td>
                        </tr>
                      </tbody>
                    </table>
                    </div>
                  </div>

                </div>
              </div>
            </div>  

            <div class="col s12 m4">
              <div class="card">
                <div class="card-content">
                  <div class="row">
                    <div class="col m8 s6">
                      <h4>Sección 3</h4>
                    </div>
                    <div class="col m4 s6">
                      <p>
                        <label>
                          <input name="secc" type="radio" />
                          <span></span>
                        </label>
                      </p>                     
                    </div>
                  </div>
                 
                  <div class="row"> 
                    <div class="col m12 s12 text-center">
                      <h4>PRECIO: $10,00</h4>
                    </div>
                    <div class="col m12 s12">
                    <table>
                      <thead>
                        <tr>
                          <th></th>
                        </tr>
                      </thead>

                      <tbody>
                        <tr>
                          <td>Una sección de medición</td>
                        </tr>
                        <tr>
                          <td>Una sección de cuchilla de servicio</td>
                        </tr>
                        <tr>
                          <td>Tres secciones de interruptor</td>
                        </tr>
                      </tbody>
                    </table>
                    </div>
                  </div>

                </div>
              </div>
            </div> 

          </div>

        </div>
      </div>
    </div>
  <!-- E N D   S E C C I O N E S-->
</div>


  <!-- T E R M I N A R   P R O C E S O -->
<div class="row">
	<div class="col m12 s12 text-center">
		<a class="btn modal-trigger" href="#modal1">Terminar Proceso</a>	
	</div>
</div>

  
  <div id="modal1" class="modal modal-fixed-footer">
    <div class="modal-content">
    	<span class="subtitle_view">Terminar Proceso de Subestaciones</span>
    	
    	<div class="row">
    		<div class="col m12 s12" style="margin-top: 20px;">
    			<h4>Datos Seleccionados</h4>
    		</div>

    		<div class="col m2 s12"></div>
    		<div class="col m8 s12">
      			<table>
        			<thead>
          				<tr>
              				<th></th>
              				<th>Opción</th>
          				</tr>
        			</thead>

        			<tbody>
          				<tr>
            				<td>Subestaciones</td>
            				<td>
            					<label id="subestacion_terminar">No seleccionada</label>
            				</td>
          				</tr>
				        <tr>
				            <td>Alcance</td>
				            <td>
				            	<label id="alcance_terminar">No seleccionada</label>
				            </td>
				        </tr>
				        <tr>
				            <td>Pruebas</td>
				            <td>
				            	<label id="prueba_terminaruno"></label><label id="prueba_terminar">No seleccionada</label>
				            </td>
				        </tr>
        			</tbody>
      			</table>
    		</div>
    		<div class="col m2 s12"></div>
    	</div>
    </div> 
    <div class="modal-footer">
      	<button class=" btn" id="add_pasouno">Guardar</button>
      	<button  class="modal-close red btn">Cerrar</button>
    </div>
  </div>


<form action="/cotizacion/requestaddcotizacion" method="POST" enctype="multipart/form-data" id="submit_subestaciones">
	<input type="hidden" name="subestacion" id="form_subestaciones" value="">
	<input type="hidden" name="alcance" id="form_alcance" value="">
	<input type="hidden" name="pruebas" id="form_prueba" value="">
</form>


<script type="text/javascript">

  	$(document).ready(function(){
    	$('.modal').modal();
  	});

	$(".subestcion_op").click(function(){
		var id = $(this).data('id');
		var descripcion = $(this).data('descripcion');
		$('#subestacion_terminar').html(descripcion); 
		console.log("ID subestacion: "+id);

		$("#subestacion_pendiente").hide();
		$("#subestacion_seleccionada").show();

		document.getElementById("form_subestaciones").value= id;
	});

	$(".alcance_op").click(function(){
		var id = $(this).data('id');
		var descripcion = $(this).data('descripcion');
		$('#alcance_terminar').html(descripcion);
		console.log("ID alcance: "+id);

		$("#alcance_pendiente").hide();
		$("#alcance_seleccionada").show();

		document.getElementById("form_alcance").value= id;
	});

	$(".prueba_op").click(function(){
		var id = $(this).data('id');
		var descripcion = $(this).data('descripcion');
		var prueba = $(this).data('prueba');
		$('#prueba_terminar').html(descripcion);
		$('#prueba_terminaruno').html(prueba+": ");
		console.log("ID prueba: "+id);

		$("#pruebas_pendiente").hide();
		$("#pruebas_seleccionada").show();

		document.getElementById("form_prueba").value= id;
	});

	$("#add_pasouno").click(function(){
    var subestacion = document.getElementById("form_subestaciones").value;
    var alcance = document.getElementById("form_alcance").value;
    var prueba = document.getElementById("form_prueba").value;

      if(subestacion == "" || alcance == "" || prueba == ""){
        swal({
          title: "Para continuar es necesario que selecciones un dato de cada seccion",
        });
      }else{
        swal("Espere un momento, la información esta siendo procesada", {
          icon: "success",
          buttons: false,
        });    
        setTimeout(submitForm, 1500);     
      }
	});

  function submitForm() {
    document.getElementById("submit_subestaciones").submit();
  }
</script>