<html>
<head>
    
    <title></title>
   <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2017.1.223/styles/kendo.common.min.css" />
<!--      <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2017.1.223/styles/kendo.black.min.css" />
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2017.1.223/styles/kendo.black.mobile.min.css" /> -->

    <script src="https://kendo.cdn.telerik.com/2017.1.223/js/jquery.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2017.1.223/js/jszip.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2017.1.223/js/kendo.all.min.js"></script>
</head>
<body>
<div id="example">

    <!-- <?php foreach ($this->eppasignado as $epp){ 

        $responsiva = $epp['id'];
        $cantidad = $epp['cantidad'];
        $comentario = $epp['comentario'];
        $talla = $epp['talla'];
        $fecha_entrega = $epp['fecha_entrega'];
        $reposicion = $epp['reposicion'];
        $id_personal = $epp['id_personal'];
        // $cobron = $epp['cobro'];
        $cobro = $epp['cobroe'];
        $tipo_epp = $epp['tipo_epp'];
        $status_epp = $epp['status_epp'];
        $id_epp = $epp['id_epp'];
        $nombre = $epp['nombre'];
        $tallen = $epp['t_e'];
        $descripcion = $epp['desc_e'];
        $stock = $epp['stock'];
        $costo_aprobado = $epp['costo_aprobado'];
        $tiempo_vida = $epp['tiempo_vida'];

    } ?>


     <?php foreach ($this->eppcobro as $epp1){ 
        $cobron = $epp1['cobro'];
    } ?>


    <?php foreach ($this->personal_epp as $personal){ 

        $idper = $personal['id']; 
        $nombrep = $personal['nombre']; 
        $apellido_pa = $personal['apellido_pa']; 
        $apellido_ma = $personal['apellido_ma']; 
        $imagen = $personal['imagen'];  
        $idpuesto = $personal['puesto'];
        $telefono = $personal['telefono']; 
        $email_personal = $personal['email_personal']; 
        $statusp = $personal['status_personal'];
        $fecha_personal = $personal['fecha_personal'];
        $idsitio = $personal['id_sitiopersonal']; 
        $name_sitio = $personal['name_sitio'];
        $npuesto = $personal['name_puesto']; 
    } ?> -->

    <?php 
            date_default_timezone_set('America/Mexico_City');
            $hoy = date("d/m/Y");
    ?>

<div class="row" style="margin-top: 10px;">
    <div class="col m6 s6">
        <a href="/cotizacion/crearcotizacion" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>
    </div>

    <div class="col m6 s6 text-right">
        <button class="export-pdf btn" onclick="getPDF('.pdf-page')">Descargar Cotización</button>
    </div>
</div>


<div class="page-container hidden-on-narrow">
    <div class="pdf-page size-a4">

        <div class="pdf-header">
            <span class="invoice-number2">
                <img src="/img/giimsa.jpg" style="width: 100px " />
            </span>

            <span class="invoice-numbercenter">
                Certificado de acuerdo a la norma ISO 9001:2015 por Applus+
            </span>
            
            <span class="invoice-number">
                <img src="/img/iso90001.png" style="width: 45px;" />
            </span>

            <div class="row">
                <div class="fecha-cot col m12 s12 text-right">
                    Ciudad de México, 02 de Junio de 2021
                </div>
            </div>  
        </div>


        <div class="pdf-footer">
            <!-- <p>Fecha de descarga: <?php echo $hoy; ?><br/>
                <span style="font-size:12px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Gps Constructivos
                </span>
            </p> -->
            <img src="/img/head.jpg" style="width:720px;" />
        </div>
                                                                                                                
        <div class="for" style="margin-top: 3px;">
            <!-- h3> Datos del Personal</h3> -->
            <p style="padding-bottom: 0px;">Hospital Infantil Privado</p>
            <p style="padding-bottom: 0px;">Star Médica</p>
            <p style="padding-bottom: 0px;">Nueva York #15</p>
            <p style="padding-bottom: 0px;">Col. Nápoles Ciudad de México</p>
            <p style="padding-bottom: 0px;">Lic. Marlene Arellano Gama</p>
            <p style="padding-bottom: 0px;">Ejecutivo de Compras Insumos y Servicios</p>
        </div>

        <div class="from text-center" style="margin-top: 15px;">
            <p style="padding-bottom: 0px;">IDC-801.2</p>
            <p style="padding-bottom: 0px;">Cotización</p>
            <p style="padding-bottom: 0px;">PS/54/2021/ALCG</p>
        </div>

        <div class="pdf-txt text-center" style="margin-top:3px;">
            <span>Presentamos a su atenta consideración nuestro presupuesto por los servicios que a continuación se describen:</span>
        </div>

        <div class="pdf-body" style="margin-top:10px;">

            <div class="row">
              <!--   <div class="col m12 s12 text-center">
                    <span style="font-size:15px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold; ">EPP Entregado
                    </span><br><br>
                </div> -->

                <div class="col m12 s12">
                    <table class="table table-sm">
                        <thead>
                            <tr>
                                <th class="text-left" style="border-style:dashed; border-width:1px; border-bottom-color:#000; border-bottom-style:solid; border-bottom-width:1px; border-top-color:#000; border-top-style:solid; border-top-width:1px;"><span style="font-size: 11px;" class="title-pdf">SUBESTACIÓN</span></th>
                                <th class="text-left" style="border-style:dashed; border-width:1px; border-bottom-color:#000; border-bottom-style:solid; border-bottom-width:1px; border-top-color:#000; border-top-style:solid; border-top-width:1px;"><span style="font-size: 11px;" class="title-pdf">ALCANCE</span></th>
                            </tr>
                        </thead>


                        <tbody>

                            <tr>
                                <td style="width: 180px; padding: 0px 10px;">
                                    <span style="font-size: 10px;">1 Sección de equipo de medición</span><br>
                                    1 Sección de cuchilla de servicio<br>
                                    1 Sección de interruptor general<br>
                                    3 Secciones de interruptores derivados.
                                </td>
                                
                                <td style="padding: 0px 10px;">
                                    Limpieza general interna y externa<br>
                                    Limpieza, revisión y apriete de buses.<br>
                                    Limpieza, revisión y apriete de aisladores<br>
                                    Limpieza, revisión y apriete de apartarrayos<br>
                                    Limpieza, revisión y apriete de interruptores<br>
                                    Ajuste, lubricación y limpieza de cuchillas de servicio<br>
                                    Revisión, lubricación y limpieza de interruptores en SF6<br>
                                    Apriete y revisión de conexiones y puntos de unión <br> 
                                    Revisión de elementos aislantes y apriete de conexiones<br>
                                    Pruebas de resistencia de aislamientos en bus, apartarrayos y aisladores<br>
                                    Pruebas de resistencia de contactos.
                                </td>
                            </tr>

                        </tbody>
                    </table>
                </div>
            </div>


            <div class="row">
                <div class="col m12 s12">
                    <table class="table table-sm">
                        <thead>
                            <tr>
                                <th class="text-left" style="border-style:dashed; border-width:1px; border-bottom-color:#000; border-bottom-style:solid; border-bottom-width:1px; border-top-color:#000; border-top-style:solid; border-top-width:1px;"><span style="font-size: 11px;" class="title-pdf">TRANFORMADORES</span></th>
                                <th class="text-left" style="border-style:dashed; border-width:1px; border-bottom-color:#000; border-bottom-style:solid; border-bottom-width:1px; border-top-color:#000; border-top-style:solid; border-top-width:1px;"><span style="font-size: 11px;" class="title-pdf">ALCANCE</span></th>
                            </tr>
                        </thead>


                        <tbody>

                            <tr>
                                <td style="width: 180px; padding: 0px 10px;">
                                    <span style="font-size: 10px;">
                                        1 Pza. Transformador de 1000 KVA, tipo “SUBESTACION” enfriamiento “OA” voltaje primario 23 KV, conexión DELTA, voltaje secundario 480/277 Volts, conexión ESTRELLA.
                                    </span><br><br>
                                    <span style="font-size: 10px;">
                                        1 Pza. Transformador de 500 KVA, tipo “PEDESTAL” voltaje primario 23 KV, conexión DELTA, voltaje secundario 480/277 Volts, conexión ESTRELLA..
                                    </span><br>
                                </td>
                                
                                <td style="padding: 0px 10px;">
                                    Limpieza general con líquido dieléctrico.<br>
                                    <b>FILTRADO Y DESGASIFICADO DE LIQUIDO AISLANTE</b><br>
                                    <b>1.-Equipo utilizado</b><br>
                                    Se usa equipo filtrador de alto vacío, con sistema de calentamiento y con capacidad necesaria para realizar el reciclado en tiempo normal<br>
                                    <b>2.-Resultados</b><br>
                                    Mejorar las propiedades dieléctricas del aire con su rigidez, tensión superficial, disminución del contenido de PPM de agua, mejorar su factor de potencia y reducción de sólidos.<br>
                                    <b>PRUEBA DE RIGIDEZ DIELÉCTRICA</b><br>
                                    1.- Objetivo del servicio.<br>
                                    Prevenir la contaminación del aceite.<br>
                                    2.- Alcance.<br>
                                    Esta prueba debe efectuarse a todo transformador para prevenir daños, tanto en los aislamientos como en los devanados y el mismo aceite.<br>
                                    3.- Equipo utilizado.<br>
                                    Probador de aceite marca HIPOTRONIC con rango de 0-100 KV.<br>
                                    4.- Resultados.<br>
                                    Asegurar el buen funcionamiento del equipo.<br>
                                    <b>PRUEBAS DE RESISTENCIA DE AISLAMIENTOS</b><br>
                                    1.- Objetivo.<br>
                                    Determinar la condición en el cual se encuentran los aislamientos.<br>
                                    2.- Alcance.<br>
                                    Se aplica a todo tipo de transformadores y de cualquier capacidad. Para determinar el estado de los aislamientos.<br>
                                    3.- Equipo Utilizado.<br>
                                    Megger digital 0-5000 volts c.d.<br>
                                    4.- Resultados.<br>
                                    Asegurar la correcta operación del equipo instalado.<br>
                                    5.- Recomendaciones.<br>
                                    Efectuar mantenimiento periódicamente programado como máximo cada año.<br>
                                </td>
                            </tr>

                        </tbody>
                    </table>
                </div>
            </div>



            <!-- <div class="row signature">
                <div class="col m6 s6 text-center">
                    <span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Entregado por:</span><br><br><br>
                    <hr>
                    <span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Nombre y Firma</span>
                </div>
                <div class="col m6 s6 text-center">
                    <span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Recibido por:</span><br><br>
                    <?php echo $nombrep; ?> <?php echo $apellido_pa; ?> <?php echo $apellido_ma; ?>
                    <hr>
                    <span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Nombre y Firma</span>
                </div>
            </div> -->
        </div>
    </div>
</div>

<div class="responsive-message"><br> </div>

 

    <style>
        .pdf-page {
            font-family: Arial Narrow,Arial,sans-serif;
        }
    </style>

    <script>
        kendo.pdf.defineFont({
            "DejaVu Sans"             : "https://kendo.cdn.telerik.com/2021.2.511/styles/fonts/DejaVu/DejaVuSans.ttf",
            "DejaVu Sans|Bold"        : "https://kendo.cdn.telerik.com/2016.2.607/styles/fonts/DejaVu/DejaVuSans-Bold.ttf",
            "DejaVu Sans|Bold|Italic" : "https://kendo.cdn.telerik.com/2016.2.607/styles/fonts/DejaVu/DejaVuSans-Oblique.ttf",
            "DejaVu Sans|Italic"      : "https://kendo.cdn.telerik.com/2016.2.607/styles/fonts/DejaVu/DejaVuSans-Oblique.ttf"
        });
    </script>

    <!-- Load Pako ZLIB library to enable PDF compression -->
    <script src="../content/shared/js/pako.min.js"></script>

    <script>
      function getPDF(selector) {
        kendo.drawing.drawDOM($(selector)).then(function(group){
          kendo.drawing.pdf.saveAs(group, "Cotizacion.pdf");
        });
      }

    $(document).ready(function() {
        var data = [
          { productName: "QUESO CABRALES", unitPrice: 21, qty: 5 },
          { productName: "ALICE MUTTON", unitPrice: 39, qty: 7 },
          { productName: "GENEN SHOUYU", unitPrice: 15.50, qty: 3 },
          { productName: "CHARTREUSE VERTE", unitPrice: 18, qty: 1 },
          { productName: "MASCARPONE FABIOLI", unitPrice: 32, qty: 2 },
          { productName: "VALKOINEN SUKLAA", unitPrice: 16.25, qty: 3 }
        ];
        var schema = {
          model: {
            productName: { type: "string" },
            unitPrice: { type: "number", editable: false },
            qty: { type: "number" }
          },
          parse: function (data) {
                $.each(data, function(){
                    this.total = this.qty * this.unitPrice;
                });
                return data;
          }
        };
        var aggregate = [
          { field: "qty", aggregate: "sum" },
          { field: "total", aggregate: "sum" }
        ];
        var columns = [
          { field: "productName", title: "Product", footerTemplate: "Total"},
          { field: "unitPrice", title: "Price", width: 120},
          { field: "qty", title: "Pcs.", width: 120, aggregates: ["sum"], footerTemplate: "#=sum#" },
          { field: "total", title: "Total", width: 120, aggregates: ["sum"], footerTemplate: "#=sum#" }
        ];
        var grid = $("#grid").kendoGrid({
          editable: false,
          sortable: true,
          dataSource: {
            data: data,
            aggregate: aggregate,
            schema: schema,
          },
          columns: columns
        });

        $("#paper").kendoDropDownList({
          change: function() {
            $(".pdf-page")
              .removeClass("size-a8")
              .removeClass("size-a4")
              .removeClass("size-letter")
              .removeClass("size-executive")
              .addClass(this.value());
          }
        });
    });
    </script>
    <style>

        .title-pdf{
            font-weight: bold;
            font-size: 13px;
            left: .4in;
        }
        .pdf-page {
            margin: 0 auto;
            box-sizing: border-box;
            box-shadow: 0 5px 10px 0 rgba(0,0,0,.3);
            background-color: #fff;
            color: #333;
            position: relative;
        }
        .pdf-header {
            position: absolute;
            top: .1in;
            height: .6in;
            left: .4in;
            right: .4in;
            /*border-bottom: 1px solid #e5e5e5;*/
        }
        .invoice-number {
            padding-top: .17in;
            float: right;
        }
        .invoice-number2 {
            padding-top: .17in;
            float: left;
        }

        .invoice-numbercenter {
            padding-top: .35in;
            float: left;
            padding-left: .70in;
            padding-right: .70in;
            font-family: Calibri,Candara,Segoe,Segoe UI,Optima,Arial,sans-serif;
            font-size: 16px;
            font-style: italic;
            font-weight: bold; 
        }

        .for {
            position: absolute;
            top: 1.5in;
            left: .4in;
            width: 3.5in;
            font-size: 13px;
            font-weight: bold;
        }
        .from {
            position: absolute;
            top: 1.5in;
            left: 5.0in;
            /*right: .4in;*/
            width: 3.5in;
            font-size: 13px;
            font-weight: bold;
        }
        .from p, .for p {
            font-family: Arial Narrow,Arial,sans-serif;
            color: #000;
        }

        .fecha-cot {
            font-size: 13px;
            font-family: Arial Narrow,Arial,sans-serif;
        }

        .pdf-txt {
            position: absolute;
            top: 3in;
            bottom: 1.2in;
            left: .4in;
            font-size: 13px;
            font-family: Arial Narrow,Arial,sans-serif;
            color: #000;
        }

        .pdf-footer {
            position: absolute;
            bottom: .5in;
            height: .6in;
            left: .4in;
            right: .4in;
            padding-top: 10px;
            /*border-top: 1px solid #e5e5e5;*/
            text-align: left;
            color: #787878;
            font-size: 12px;
        }
        .pdf-body {
            position: absolute;
            top: 3.4in;
            bottom: 1.2in;
            left: .4in;
            right: .4in;
            font-family: Arial Narrow,Arial,sans-serif;
        }

        th{
            /*padding: 1px 5px;*/
            font-family: Arial Narrow,Arial,sans-serif;
            color: #000;
            font-weight: bold;
        }

        tr{
            /*padding: 1px 3px;*/
            font-family: Arial Narrow,Arial,sans-serif;
            color: #000;
            font-size: 10px;
        }
        
        td{
            border-style:dashed;  
            border-width:1px; 
            border-bottom-color:#000; 
            border-bottom-style:solid; 
            border-bottom-width:1px; 
            border-top-color:#000; 
            border-top-style:solid; 
            border-top-width:1px;
            font-family: Arial Narrow,Arial,sans-serif;
            color: #000;
        }


        .size-a5 { width: 8.3in; height: 5.8in; }
        .size-a4 { width: 8.3in; height: 11.7in; }
        .size-letter { width: 8.5in; height: 11in; }
        .size-executive { width: 7.25in; height: 10.5in; }

        .company-logo {
            font-size: 30px;
            font-weight: bold;
            color: green;
        }
        
        .signature {
            padding-top: .4in;
        }
    </style>

</div>


</body>
