<div class="row">
    <div class="col s12 m12"  style="margin-top: 20px;">
      	<div class="card">
	        <div class="card-content">
				<div class="row">
				    <div class="col m12 s12 text-center">
				      <span class="title_view">Modulo de Transformadores</span>
				    </div>
				</div>

				<div class="row" style="margin-top: 25px;">
					<div class="col m3 s6 text-center"> 
				      	<div class="chip">
				      		<img src="/img/correct.png">
				      		Tipo
				      	</div>
					</div>

					<div class="col m3 s6 text-center"> 
						<a href="/subestacion/alcancessubesatcion">
					      	<div class="chip">
					      		<img src="/img/gris.jpg">
					      		Alcances
					      	</div>
				      	</a>
					</div>

					<div class="col m3 s6 text-center"> 
						<a href="/subestacion/pruebassubestacion">
					      	<div class="chip">
					      		<img src="/img/gris.jpg">
					      		Analisis
					      	</div>
				      	</a>
					</div>

					<div class="col m3 s6 text-center"> 
				      	<div class="chip">
				      		<img src="/img/gris.jpg">
				      		Pruebas
				      	</div>
					</div>

				</div>
	        </div>
      	</div>
    </div>
</div>
