<?php 
	function isActhref($nameBtn,$urlname){
	    if($nameBtn==1 && $urlname==null){
	    	return "active"; 
	    }
	    return ($nameBtn == $urlname)?"active":"";
	}

    if (isset($_GET['pagina'])) {
        $pagina = $_GET['pagina'];
    } else {
        $pagina = 1;
    }  
?>

<?php 

    $links = "";
    $url="";

        if($this->total== 1){
            $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
        }else{
            if ($this->total >= 1 && $pagina <= $this->total) {

              if (isset($_GET['pagina']) && $this->actpage != 1) {
                $links .= "<li class=\"page-item\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }else{
                $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }
                
                $i = max(2, $pagina - 3);
                if ($i > 2)
                    $links .= " <li><a>...</a></li> ";
                for (; $i < min($pagina + 3, $this->total); $i++) {
                  if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }else{
                    $links .= "<li class=\"page-item \" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }
                }
                if ($i != $this->total)
                    $links .= " <li><a>...</a></li> ";
                if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }else{
                    $links .= "<li class=\"page-item\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }
                
            }           
        }


 ?>

<div class="row">
    <div class="col s12 m12"  style="margin-top: 20px;">
      	<div class="card">
	        <div class="card-content">
				<div class="row">
				    <div class="col m12 s12 text-center">
				      <span class="title_view">Modulo de Subestaciones</span>
				    </div>
				</div>

				<div class="row" style="margin-top: 25px;">
					<div class="col m3 s6 text-center">
						<a href="/subestacion/subestaciones"> 
					      	<div class="chip">
					      		<img src="/img/gris.jpg">
					      		Subestaciones
					      	</div>
				      	</a>
					</div>

					<div class="col m3 s6 text-center"> 
						<a href="/subestacion/alcancessubesatcion"> 
						    <div class="chip">
						      	<img src="/img/gris.jpg">
						      	Alcances
						    </div>
					    </a>
					</div>

					<div class="col m3 s6 text-center"> 
				      	<div class="chip">
				      		<img src="/img/correct.png">
				      		Pruebas
				      	</div>
					</div>

					<div class="col m3 s6 text-center"> 
						<a href="/subestacion/seccionessubestacion"> 
					      	<div class="chip">
					      		<img src="/img/gris.jpg">
					      		Secciones
					      	</div>
				      	</a>
					</div>

				</div>
	        </div>
      	</div>
    </div>
</div>

<div class="row">
	<div class="col m12 s12" style="margin-top: 20px;">
		<div class="row">
			<div class="col m6 s6">
				<span class="subtitle_view">Pruebas</span>
			</div>
			<div class="col m6 s6 text-right">
				<a class="btn modal-trigger" href="#modal1"> <i class="material-icons left">playlist_add</i>Agregar Prueba</a>
			</div>
		</div>
		
		<table class="table text-left table-hover">
			<thead>
				<tr>
					<th>Id.</th>
					<th>Prueba</th>		
          			<th>Descripción</th>
          			<th></th>
					<!-- <th>Eliminar</th> -->
				</tr> 
			</thead>
			<?php
			if ($this->paginator) { 
			foreach ($this->paginator as $usr) { ?>
			<tbody>
				<tr>
					<td>
						<?php echo $usr['ID_PRUEBA']; ?>
					</td>
					<td>
						<?php echo $usr['PRUEBA']; ?>
					</td>
					<td>
						<?php echo $usr['DESCRIPCION']; ?>
					</td>
					<td>
						<a href="/panel/usuariodetail/id/<?php echo $usr["ID_PRUEBA"]; ?>"><i class="fa fa-2x fa-edit"></i></a>	
					</td>
					<td>
						<a class="delete" data-id="<?php echo $usr["ID_PRUEBA"]; ?>"><span class="warning"><i class="fa fa-2x fa-trash" style="color: red"></i></span></a>
					</td>

				</tr>
		    <?php } }else{ ?>
		    </tbody> 
		    <tbody>
		        <tr>
		            <td class="text-center" colspan="6"><h4>No hay alcances.</h4></td>
		        </tr>
		    </tbody>
		                
		    <?php } ?>
		</table>
	</div>
</div>


<div class="row">
    <div class="col m12 s12 text-center">
        <div class="white-box">
            <div class="paginationControl">
                <ul class="pagination justify-content-center">
               		<?php if($pagina - 1 == 0){ ?>
                    	<li class="page-item disabled">
                        	<span class="page-link">Anterior</span>
                    	</li>
               		<?php }else{ ?>
                        <li class="page-item">
                            <a class="page-link <?php if($pagina <= 1){ echo 'disabled'; } ?> " href="<?php if($pagina <= 1){ echo '#'; } else { echo "?pagina=".($pagina - 1); } ?>"> Anterior </a>
                        </li>
               		<?php } ?>
                        <li class="page-item <?php echo isActhref($links,$this->actpage);?>">
                            <?php echo $links; ?>
                        </li>
               		<?php if($pagina >= $this->total): ?>
                       	<li class="page-item disabled">
                            <span class="page-link">Siguente</span>
                       	</li>
                    <?php else: ?>
                        <li class="page-item">
                            <a class="page-link"  href="<?php echo "?pagina=".($pagina + 1); ?>">Siguiente</a>
                        </li>
                   	<?php endif; ?>
                </ul>
            </div>
        </div>
    </div> 
</div>

<div id="modal1" class="modal modal-fixed-footer">
    <div class="modal-content">
      	<span class="subtitle_view">Agregar Alcance</span>
      
      	<div class="row">
      		<form action="/subestacion/requestaddpruebas" method="POST" enctype="multipart/form-data" id="submit_subestacio">
      		<div class="col m12 s12" style="margin-top: 20px;">
		        <div class="input-field col s12">
		         	<input id="prueba" name="prueba" type="text" class="validate">
		          	<label for="prueba">Prueba</label>
		        </div>

		        <div class="input-field col s12">
		         	<input id="descripcion" name="descripcion" type="text" class="validate">
		          	<label for="descripcion">Descripción</label>
		        </div>
	      	</div>  
	      	</form>   		
      	</div>
	

    </div>
    <div class="modal-footer">
      	<button class=" btn" id="add_subestacion">Guardar</button>
      	<button  class="modal-close red btn">Cerrar</button>
    </div>
</div>



<script type="text/javascript">
	$(document).ready(function(){
    	$('.modal').modal();
  	});

  	$("#add_subestacion").click(function(){
	    var descripcion = document.getElementById("descripcion").value;
	    var prueba = document.getElementById("prueba").value;

      if(descripcion == "" || prueba == ""){
        swal({
          title: "Para continuar es necesario agregar ambos campos solicitados",
        });
      }else{
        swal("Espere un momento, la información esta siendo procesada", {
          icon: "success",
          buttons: false,
        });    
        setTimeout(submitForm, 1500);     
      }
  	});

  	function submitForm() {
    	document.getElementById("submit_subestacio").submit();
  	}	

    $(".delete").click(function(){
    	var id = $(this).data('id');
    	var table ="GIM_PRUEBAS";
    	var where = "ID_PRUEBA";

		swal({
			title: "Estas seguro de eliminar la prueba?",
			icon: "warning",
			buttons: true,
			dangerMode: true,
		})
		.then((willDelete) => {
		  	if (willDelete) {
				swal("Espere un momento, la información esta siendo procesada", {
					icon: "success",
					buttons: false,
				});
	            var request = $.ajax({
	                url:"/subestacion/requestdeletesubestacion",
	                method:"POST",
	                data: { id : id, table:table, where:where},
	                processData: true,
	            });
				//-------------------end de ajax---------------------------
				//---------	----peticion de respuesta de ajax------------------
	            request.done(function(response) {
	                console.log(response);//imprime lo que responde el ajax
	                window.location.reload(true);
	            });
				//-------------------end de respuesta ajax---------------------
	             return false;
		  	} else {
		    	swal("La asignacion fue cancelada!");
		  	}
		});
    });
</script>