<section class="content">

    <div class="row">

        <div class="col s12 m12">

            <div class="box">

                <div class="box-header with-border">

                    <h3 class="box-title">Registrar Productos</h3>

                </div>

                <div class="box-body">

                    <form role="form" method="POST" action="/alcances/getinfo" id="FormData"  enctype="multipart/form-data">

                        <input type="hidden" name="optReg" value="set">

                        <input type="hidden" id="catId" name="catId" value="<?php echo $this->catId; ?>">

                        <div class="row">

                            <div class="col s8 m8">
                                    
                                <div class="row">

                                    <div class="col s12 m12">
                                        
                                        <div class="form-group">

                                            <label for="inputTIPO" class="col-xs-3 col-md-3 col-sm-3">Tipo</label>

                                            <div class="input-group col-xs-9 col-md-9 col-sm-9">

                                                <select class="form-control required" name="ID_TIPO">

                                                    <option value="">Seleccione una opcion...</option>

                                                    <?php foreach ( $this->aData as $key => $value): ?>

                                                        <option value="<?php print $value['TIPO'] ?>"><?php print $value['CBO_DESCRIPCION'] ?></option>
                                                        
                                                    <?php endforeach; ?>                               

                                                </select>

                                            </div>

                                        </div>
                                        
                                        <div class="form-group">

                                            <label for="inputDESCRIPCION" class="col-xs-3 col-md-3 col-sm-3">Descripción</label>

                                            <div class="input-group col-xs-9 col-md-9 col-sm-9">

                                                <input class="form-control required" name="DESCRIPCION" placeholder="Descripcion" value="<?php print @$this->aData[0]['DESCRIPCION'] ?>">

                                                <div class="form-group">

                                                </div>   

                                            </div>

                                        </div>   
                                        
                                        <div class="form-group">

                                            <div class="switch col s9 m9">
                                                
                                                <label>

                                                  Inactivo
                                                  
                                                  <input name="ACTIVO" type="checkbox">
                                                  
                                                  <span class="lever"></span>

                                                  Activo
                                                
                                                </label>

                                            </div>

                                        </div> 

                                    </div>

                                </div>
                                
                            </div>

                        </div>

                        <div class="box-footer col-xs-12 col-md-12 col-sm-12">

                            <button type="submit" class="green darken-2 btn-small">Guardar Datos</button>

                            <a type="button" class="deep-orange darken-4 btn-small" href="/alcances/?tpo=<?php print $this->aResponseTipo ?>">Regresar</a>

                        </div>

                    </form>  

                    <?php if( $this->aResponse['status'] == 1 ):?>

                        <script>

                           $(document).ready( function(){
                              
                              success();
                           
                           });

                        </script>

                    <?php elseif ($this->aResponse['status'] == -1):?>

                        <script>

                           $(document).ready( function(){
                              
                              danger();
                           
                           });

                        </script>

                    <?php endif; ?>

                </div> 

            </div>

        </div>        

    </div>

</section>
                                        
<script type="text/javascript">
    
    function success(){

        swal({

            icon: "success",

            text: "Se Registro de manera Correcta",

        });

    }

    function danger(){

        swal({

            icon: "error",

            text: "Ocurrio un error al registrar el producto",

        });

    }
    
</script>
