
    

<section class="content">
 
    <div class="row">
 
        <div class="col-md-12">
 
            <div class="box">
 
                <div class="box-header with-border">
 
                    <h3 class="box-title">Servicios Alcances</h3>
 
                    <div class="pull-right">
 
                    </div>

                    <div class="box-body">

                        <div class="table-toolbar">
                    
                            <div class="pull-left" style="padding: 1%">
                    
                                <a class="btn-small green darken-2" href="/alcances/getinfo?optReg=set" data-toggle="tooltip" data-placement="bottom" data-original-title="Agregar"><i class="fa fa-plus"></i> Agregar </a>

                                <a type="button" class="deep-orange darken-4 btn-small" href="/producto/?catId=<?php echo $_GET['tpo'];?>">Regresar</a>
                    
                            </div>               
                    
                        </div> 

                        <table  class="table table-hover" id="myTable" cellpadding="1" cellspacing="1" >
                    
                            <thead> 
                    
                                <tr role="row">         

                                    <th>Servicio</th>                                              

                                    <th>Descripcion</th>                                   
                                    
                                    <th>Activo</th>                                   
                                    
                                    <th></th>

                                    <th></th>                                   
                    
                                </tr>                                
                    
                            </thead>                     
                    
                            <tbody>        
                    
                                <?php if(count($this->aData)>0):?> 
                    
                                    <?php foreach($this->aData as $k => $v): ?>  

                                        <tr class="odd gradeX">

                                            <td><?php print $v['SERVICIO'];  ?></td>             

                                            <td><?php print $v['DESCRIPCION'];  ?></td>

                                            <td><?php print $v['ACTIVO'];  ?></td> 

                                            <td class="center-align">  

                                               <a href="/alcances/upalcances?catId=<?php echo $v['ID_ALCANCE'];?>&optReg=up"><i class="fa fa-2x fa-edit"></i></a>

                                            </td>   

                                            <td class="center-align">

                                               <a class="delete" href="/alcances/delete?catId=<?php echo $v['ID_ALCANCE'];?>&optReg=up" ><span class="warning"><i class="fa fa-2x fa-trash" style="color: red"></i></span></a>
 
                                            </td>

                                        </tr>   

                                    <?php endforeach;?>

                                <?php endif;?>

                            </tbody>

                        </table>

                        <div class="col-md-12 center text-center">

                            <span class="left" id="total_reg"></span>

                            <ul class="pagination pager" id="myPager"></ul>

                        </div>

                    </div> 

                </div>

            </div>        

        </div>

    </div>

</section>

<script>

$(document).ready(function(){

  $('#myTable').pageMe({

    pagerSelector:'#myPager',

    activeColor: 'blue',

    prevText:'Anterior',

    nextText:'Siguiente',

    showPrevNext:true,

    hidePageNumbers:false,

    perPage:6

  });

});

</script>

<?php if( $_GET['del'] == 1 ):?>

    <script>

       $(document).ready( function(){
          
          success();
       
       });

    </script>

<?php elseif ( $_GET['del'] == -1):?>

    <script>

       $(document).ready( function(){
          
          danger();
       
       });

    </script>

<?php endif; ?>


<script type="text/javascript">
    
    function success(){

        swal({

            icon: "success",

            text: "Se elimino de manera Correcta",

        });

    }

    function danger(){

        swal({

            icon: "error",

            text: "Ocurrio un error al eliminar",

        });

    }
    
</script>


<!--

    butonones agregar -- green darken-2

    editar --  light-blue darken-2

    eliminar .-- deep-orange darken-4



    -->