<?php $this->headScript()->appendFile('') ?> 

<section class="content">
 
    <div class="row">
 
        <div class="col-md-12">
 
            <div class="box">
 
                <div class="box-header with-border">
 
                    <div class="row">

                        <div class="col s12 m12"  style="margin-top: 20px;">

                            <div class="card">

                                <div class="card-content">

                                    <div class="row">

                                        <div class="col m12 s12 text-center">

                                          <span class="title_view"><?php print $this->aData[0]['CATALOGO_NOMBRE']; ?></span>

                                        </div>

                                    </div>

                                    <div class="row" style="margin-top: 25px;">

                                        <div class="col m3 s6 text-center"> 

                                            <a href="/producto/?catId=<?php echo $_GET['tpo'];?>">

                                                <div class="chip">

                                                    <img src="/img/correct.png">

                                                    <?php print $this->aData[0]['CATALOGO_NOMBRE']; ?>

                                                </div>

                                            </a>

                                        </div>

                                        <div class="col m3 s6 text-center"> 

                                            <a href="/alcances/index?tpo=<?php print $_GET['tpo'] ?>">

                                                <div class="chip">

                                                    <img src="/img/gris.jpg">

                                                    Alcances

                                                </div>

                                            </a>

                                        </div>

                                        <div class="col m3 s6 text-center"> 

                                            <a href="/pruebas/">

                                                <div class="chip">

                                                    <img src="/img/gris.jpg">

                                                    Pruebas

                                                </div>

                                            </a>

                                        </div>

                                        <div class="col m3 s6 text-center"> 

                                            <a href="/subestacion/seccionessubestacion"> 

                                                <div class="chip">

                                                    <img src="/img/gris.jpg">

                                                    Secciones

                                                </div>

                                            </a>

                                        </div>

                                    </div>

                                </div>

                            </div>

                        </div>

                    </div>

                    <div class="box-body">

                        <div class="table-toolbar">
                    
                            <div class="pull-left" style="padding: 1%">
                    
                                <a class="btn-small green darken-2" href="/producto/getinfoplanta?tpo=<?php print $_GET['tpo']?>" data-toggle="tooltip" data-placement="bottom" data-original-title="Agregar"><i class="fa fa-1x fa-plus"></i> Agregar planta de emergencia</a>
                    
                            </div>                
                    
                        </div> 

                        <table  class="table text-left table-hover">
                    
                            <thead> 
                    
                                <tr role="row">                                                       

                                    <th>Capacidad</th>

                                    <th>Precio</th>

                                    <th>Estatus</th>

                                    <th></th>

                                    <th></th>                                   
                    
                                </tr>                                
                    
                            </thead>                     
                    
                            <tbody>        
                    
                                <?php if(count($this->aData)>0):?> 
                    
                                    <?php foreach($this->aData as $k => $v): ?>  

                                        <tr class="odd gradeX">                                    

                                            <td><?php print $v['CAPACIDAD'];  ?></td>

                                            <td>$ <?php print number_format($v['PRECIO'],2);  ?></td>

                                            <td><?php print $v['ACTIVO'];  ?></td>
                    
                                            <td>

                                            	<a href="/producto/upgetinfoplanta?catId=<?php echo $v["ID_PLANTA"] ?>"><i class="fa fa-1x fa-edit"></i></a>

                                            </td>

                                            <td>

                                            	<a class="delete" href="/producto/plantasemergencia/?catId=<?php echo $v["ID_PLANTA"]; ?>&op=del" ><span class="warning"><i class="fa fa-1x fa-trash" style="color: red"></i></span></a>

                                            </td>
                                        </tr>   

                                    <?php endforeach;?>

                                <?php endif;?>

                            </tbody>

                        </table>

                    </div> 

                </div>

            </div>        

        </div>

    </div>

</section>

<?php if( $_GET['del'] == 1 ):?>

    <script>

       $(document).ready( function(){
          
          success();
       
       });

    </script>

<?php elseif ( $_GET['del'] == -1):?>

    <script>

       $(document).ready( function(){
          
          danger();
       
       });

    </script>

<?php endif; ?>


<script type="text/javascript">
    
    function success(){

        swal({

            icon: "success",

            text: "Se elimino de manera Correcta",

        });

    }

    function danger(){

        swal({

            icon: "error",

            text: "Ocurrio un error al eliminar",

        });

    }
    
</script>


<!--

    butonones agregar -- green darken-2

    editar --  light-blue darken-2

    eliminar .-- deep-orange darken-4



    -->
