<section class="content">

    <div class="row">

        <div class="col s12 m12">

            <div class="box">

                <div class="box-header with-border">

                    <h3 class="box-title"><b>PLANTAS EMERGENCIA</b></h3>

                </div>

                <div class="box-body">

                    <form role="form" method="POST" action="/producto/upgetinfoplanta" id="FormData"  enctype="multipart/form-data">

                        <input type="hidden" name="optReg" value="set">

                        <input type="text" id="catId" name="ID_UPDATE" value="<?php print @$this->aData[0]['ID_PLANTA'] ?>">

                        <div class="row">

                            <div class="col s8 m8">
                                    
                                <div class="row">

                                    <div class="col s12 m12">

                                        <div class="form-group">

                                            <label for="inputDESCRIPCION" class="col-xs-3 col-md-3 col-sm-3">Capacidad</label>

                                            <div class="input-group col-xs-9 col-md-9 col-sm-9">

                                                <input class="form-control required" name="CAPACIDAD" placeholder="Capacidad" value="<?php print @$this->aData[0]['CAPACIDAD'] ?>">

                                                <div class="form-group">

                                                </div>   

                                            </div>

                                        </div>  

                                        <div class="form-group">

                                            <label for="inputDESCRIPCION" class="col-xs-3 col-md-3 col-sm-3">Costo</label>

                                            <div class="input-group col-xs-9 col-md-9 col-sm-9">

                                                <input class="form-control required" name="COSTO" placeholder="$ 0.00" value="<?php print @$this->aData[0]['PRECIO'] ?>">

                                                <div class="form-group">

                                                </div>   

                                            </div>

                                        </div>  
                                        
                                        <div class="form-group">

                                            <div class="switch col s9 m9">
                                                
                                                <label>

                                                  Inactivo
                                                  
                                                  <input name="ACTIVO" type="checkbox" <?php print ( @$this->aData[0]['ACTIVO'] ) ? 'checked': ''; ?>>
                                                  
                                                  <span class="lever"></span>

                                                  Activo
                                                
                                                </label>

                                            </div>

                                        </div> 
 

                                    </div>

                                </div>
                                
                            </div>

                        </div>

                        <div class="box-footer col-xs-12 col-md-12 col-sm-12">

                            <button type="submit" class="green darken-2 btn-small">Guardar Datos</button>

                            <a type="button" class="deep-orange darken-4 btn-small" href="/producto/plantasemergencia?tpo=2">Regresar</a>

                        </div>

                    </form>  

                    <?php if( @$this->aResponse['status'] == 1 ):?>

                        <script>

                           $(document).ready( function(){
                              
                              success();
                           
                           });

                        </script>

                    <?php elseif (@$this->aResponse['status'] == -1):?>

                        <script>

                           $(document).ready( function(){
                              
                              danger();
                           
                           });

                        </script>

                    <?php endif; ?>

                </div> 

            </div>

        </div>        

    </div>

</section>
                                        
<script type="text/javascript">
    
    function success(){

        swal({

            icon: "success",

            text: "Se Registro de manera Correcta",

        });

    }

    function danger(){

        swal({

            icon: "error",

            text: "Ocurrio un error al registrar el producto",

        });

    }
    
</script>
