<link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Montserrat:wght@300&display=swap" rel="stylesheet">
<style type="text/css">

  .parallax-container {
    height: 50px;
    /*opacity: 0.1;*/
  }

  #prl1{
    width: 100%; height: 400px;
  }

  #logo{
    width: 100px;
  }

  .op{
    opacity: 0.3;
  }

  .container{
    width: 75%;
  }


  .container span{
    font-size: 16px;
    font-family: 'Montserrat', sans-serif;
    color: black; 
    
  }

  .container img{
    width: 200px;
    border-radius: 20px 20px 0 0;
  }

  @media screen and (max-width: 600px) {
    body {
      /*background-color: olive;*/
    }

    #prl1{
      width: 100%; height: 500px;
    }

    #logo{
      width: 100px;
    }
  }

</style>


<!-- Content -->
<div class="parallax-container center valign-wrapper"  id="prl1">
  <div class="container">
    <div class="row">
      <div class="col m12 s12 text-center">
        <span style="font-size:50px; font-family: 'Bebas Neue', cursive;  color: black; letter-spacing: 0.2em; font-weight: bold;">GIIMSA</span>
        <img src="/img/port.png" id="logo">
      </div>
    </div>
  </div>
  
  <div class="parallax op ">
    <img src="/img/portada.jpg" style="width: 300px;">
  </div>
</div>


<div class="container" style="margin-top: 25px;">
  <div class="row">
    <div class="col m12 s12 text-center">
      <span style="font-size:35px; font-family: 'Bebas Neue', cursive; color: rgb(74,79,84); letter-spacing: 0.4em;">¿QUIÉNES SOMOS?</span>
    </div>
  </div>

  <div class="row">
    <div class="col md12 s12 text-center mt-4">
      
      <div class="col m5 s12">
        <div class="icon-block text-justify">
          <h2 class="center light-blue-text">
            <img style="width: 300px;" src="/img/mision.png">  
          </h2>
               <span style="font-weight: 600;">Ser una empresa dedicada a los proyectos, suministros, montajes y servicios en instalaciones electromecánicas de alta, media y baja tensión, en constante actualización humana y tecnológica.</span>     
        </div>
      </div>

      <div class="col m2 s12"></div>

      <div class="col m5 s12">
        <div class="icon-block text-justify">
          <h2 class="center light-blue-text">
            <img style="width: 300px;" src="/img/vision.png">  
          </h2>
          <span style="font-weight: 600;">Ser una empresa líder, proporcionando el servicio, soporte y soluciones que satisfagan las necesidades y expectativas de nuestros clientes.</span>
        </div>
      </div>
<!--    <span style="font-size:25px; color: rgb(74,79,84);">Somos una empresa mexicana, <br>  
        que ofrece diversos servicios de construcción de infraestructura <br>
      para la industria de las telecomunicaciones.</span>  -->
   
    </div>
  </div>
</div>

<div class="container" style="margin-top: 25px;">
  <div class="row">
    <div class="col m12 s12">
      <span style="font-size:35px; font-family: 'Bebas Neue', cursive; color: rgb(74,79,84); letter-spacing: 0.4em;">Servicios</span>
    </div>
   </div>
</div>

<div class="container">
  <div class="row">
     <div class="col m4 s12">
       <div class="icon-block text-justify">
         <h2 class="center light-blue-text">
           <img src="/img/subestacion.jpg">  
         </h2>
         <h5 class="center">SUBESTACIONES</h5>
       </div>
       
     </div>
     <div class="col m4 s12">
       <div class="icon-block text-justify">
         <h2 class="center light-blue-text">
          <img src="/img/planta.jpg">  
         </h2>
         <h5 class="center">PLANTAS DE EMERGENCIA</h5>
       </div> 
     </div>
     <div class="col m4 s12">
       <div class="icon-block text-justify">
         <h2 class="center light-blue-text">
           <img src="/img/construccion.jpg"> 
         </h2>
         <h5 class="center">CONSTRUCCIÓN</h5>
       </div> 
     </div>
   </div>
</div>


<div class="container" style="margin-bottom: 30px;">
  <div class="row">
     <div class="col m4 s12">
       <div class="icon-block text-justify">
         <h2 class="center light-blue-text">
           <img src="/img/mantto.jpg">  
         </h2>
         <h5 class="center">MANTENIMIENTO DE TRANSFORMADORES</h5>
       </div>
       
     </div>
     <div class="col m4 s12">
       <div class="icon-block text-justify">
         <h2 class="center light-blue-text">
          <img src="/img/insta.jpg">  
         </h2>
         <h5 class="center">INSTALACIONES</h5>
       </div> 
     </div>
     <div class="col m4 s12">
       <div class="icon-block text-justify">
         <h2 class="center light-blue-text">
           <img src="/img/montaje.jpg"> 
         </h2>
         <h5 class="center">MONTAJE</h5>
       </div> 
     </div>
   </div>
</div>

<!-- https://images.unsplash.com/photo-1463780324318-d1a8ddc05a11?dpr=1&auto=format&fit=crop&w=1500&h=1000&q=80&cs=tinysrgb&crop= -->

<div class="parallax-container center valign-wrapper">
  <div class="parallax"><img src="/img/min-gs.jpg">
  </div>
  
  <div class="container white-text">
    <div class="row">
      <div class="col s12">
        <!-- <h5>A modern responsive front-end framework based on Material Design</h5> -->
      </div>
    </div>
  </div>
</div>

<div class="container center-align">
 <div class="section">
    <div class="row">
    <div class="col s12">
      <h4>Contact Us</h4>
      <p class="light left-align">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque id nunc nec volutpat. Etiam pellentesque tristique arcu, non consequat magna fermentum ac. Cras ut ultricies eros. Maecenas eros justo, ullamcorper a sapien id, viverra ultrices eros. Morbi sem neque, posuere et pretium eget, bibendum sollicitudin lacus. Aliquam eleifend sollicitudin diam, eu mattis nisl maximus sed. Nulla imperdiet semper molestie. Morbi massa odio, condimentum sed ipsum ac, gravida ultrices erat. Nullam eget dignissim mauris, non tristique erat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;
      </p>
    </div>      
  </div>
  </div>
</div>




<script type="text/javascript">
  $(document).ready(function(){
  $('.parallax').parallax();
});
</script>