<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>

<style type="text/css">
body {
  font-family: "Open Sans", sans-serif;
  height: 100vh;
  /*background: url("https://i.imgur.com/HgflTDf.jpg") 50% fixed;*/
  background: url("/img/log.jpg") 50% fixed;
  background-size: cover;
}

.wrapper {
  display: flex;
  align-items: center;
  flex-direction: column;
  justify-content: center;
  width: 100%;
  min-height: 100%;
  padding: 20px;
}

.login {
  border-radius: 5px 5px 5px 5px;
  padding: 10px 20px 20px 20px;
  width: 90%;
  max-width: 500px;
  background: #ffffff;
  position: relative;
  padding-bottom: 110px;
  box-shadow: 0px 1px 5px rgba(0, 0, 0, 0.3);
}
.login.loading button {
  max-height: 100%;
  padding-top: 50px;
}
.login.loading button .spinner {
  opacity: 1;
  top: 40%;
}
.login.ok button {
  background-color: #8bc34a;
}
.login.ok button .spinner {
  border-radius: 0;
  border-top-color: transparent;
  border-right-color: transparent;
  height: 20px;
  animation: none;
  transform: rotateZ(-45deg);
}
.login input {
  display: block;
  padding: 15px 10px;
  margin-bottom: 10px;
  width: 100%;
  border: 1px solid #ddd;
  transition: border-width 0.2s ease;
  border-radius: 2px;
  color: #ccc;
}
.login input + i.fa {
  color: #fff;
  font-size: 1em;
  position: absolute;
  margin-top: -47px;
  opacity: 0;
  left: 0;
  transition: all 0.1s ease-in;
}
.login input:focus {
  outline: none;
  color: #444;
  border-color: #2196F3;
  border-left-width: 35px;
}
.login input:focus + i.fa {
  opacity: 1;
  left: 30px;
  transition: all 0.25s ease-out;
}
.login a {
  font-size: 0.8em;
  color: #2196F3;
  text-decoration: none;
}
.login .title {
  color: #444;
  font-size: 1.2em;
  font-weight: bold;
  margin: 10px 0 30px 0;
  border-bottom: 1px solid #eee;
  padding-bottom: 20px;
}

.login button {
  width: 100%;
  height: 100%;
  padding: 10px 10px;
  background: #2196F3;
  color: #fff;
  display: block;
  border: none;
  margin-top: 20px;
  position: absolute;
  left: 0;
  bottom: 0;
  max-height: 60px;
  border: 0px solid rgba(0, 0, 0, 0.1);
  border-radius: 0 0 2px 2px;
  transform: rotateZ(0deg);
  transition: all 0.1s ease-out;
  border-bottom-width: 7px;
}

</style>


<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js"></script> -->
<!-- <div class="row center-block col-lg-offset-4 col-md-offset-2">
  <div class="white-box">
    <div class="col-lg-12 col-md-12 text-center">
      <h2>Iniciar sesion</h2> <br>       
    </div>
    <div class="col-lg-12 col-md-12">
      <h4 class="text-center inner-padding">Ingrese sus datos. </h4>
      <form method="POST" action="/index/validar">
        <div class="row">
          <div class="col-lg-12 col-md-12">
            <div class="form-group">
              <label><i class="fa fa-user" aria-hidden="true"></i> Correo</label>
              <input type="text" name="mail"  class="form-control"/>    
            </div>
            <div class="form-group">
              <label><i class="fa fa-lock" aria-hidden="true"></i> Contraseña</label>
              <input type="password" name="passw" class="form-control"/> 
              <a href="/home/recuperarcontrasena"><h6>Olvide contraseña</h6></a>
            </div>
            <div class="form-group text-center">
             <input type="submit" value="Iniciar Sesión" class="btn btn-primary"/>
           </div>
         </div>
       </div>     
     </form>
   </div>            
 </div>
</div> --> 


<!-- Login -->
<!--  <div class="row">
  <div class=" col m6 s12">
  <div class="col s12 m7">
    <h2 class="header">Iniciar sesión</h2>
    <div class="card horizontal">
      <div class="card-stacked">
        <div class="card-content">
          <form action="/index/validar" method="POST" enctype="multipart/form-data" class="form-horizontal form-material">
            <input type="hidden" name="ids" value="<?php echo $usr["id"]; ?>">
            <div class="input-field col m12 s12">
                <i class="material-icons prefix">account_circle</i>
                <input id="icon_prefix" type="text" name="mail" class="validate"  required>
                <label for="icon_prefix">Correo:</label>
            </div>

            <div class="input-field col m12 s12">
                <i class="material-icons prefix">lock</i>
                <input id="icon_telephone" type="password" name="passw"  class="validate">
                <label for="icon_telephone">contraseña:</label>
            </div>

            <div class="input-field col m12 s12 text-center">
              <div class="row">
                <div class="col m2 s12"> </div>
                <div class="col m8 s12"><button type="submit" id="add_user" class="waves-effect waves-light btn">Iniciar sesión</button></div>
                <div class="col m2 s12"></div>
                
              </div>  
            </div>
          </div>
        </form>
        </div>
        <div class="card-action">
          <a href="/home/recuperarcontrasena">Olvide contraseña</a>
        </div>
      </div>
    </div>
  </div>
  </div>
</div> -->


<div class="wrapper">
    <form  action="/index/validar" method="POST" enctype="multipart/form-data" class="login form-horizontal form-material">
        <input type="hidden" name="ids" value="<?php echo $usr["id"]; ?>">
        
        <p class="title">Iniciar Sesión</p>

        <div class="input-field col m12 s12">
            <i class="material-icons prefix">account_circle</i>
            <input id="icon_prefix" type="text" name="mail" class="validate"  required>
            <label for="icon_prefix">Correo:</label>
        </div>

        <div class="input-field col m12 s12">
            <i class="material-icons prefix">lock</i>
            <input id="icon_telephone" type="password" name="passw"  class="validate" required>
            <label for="icon_telephone">contraseña:</label>
        </div>
        <p class="alert alert-danger text-center" role="alert">Usuario y/o Contraseña Incorrectas, Intentalo de nuevo.</p>

        <button type="submit" id="add_user" class="waves-effect waves-light btn">Iniciar sesión</button>

        <!-- <div class="card-action">
            <a href="/home/recuperarcontrasena">¿Olvidaste tu contraseña?</a>
        </div> -->
    </form>
    
</div>
