<!-- <div class="row center-block col-lg-offset-4 col-md-offset-2">
  <div class="white-box">
    <div class="col-lg-12 col-md-12 text-center">
      <h2>Iniciar sesion</h2> <br>       
    </div>
    <div class="col-lg-12 col-md-12">
      <h4 class="text-center inner-padding">Ingrese sus datos. </h4>
      <form method="POST" action="/index/validar">
        <div class="row">
          <div class="col-lg-12 col-md-12">
            <div class="form-group">
              <label><i class="fa fa-user" aria-hidden="true"></i> Correo</label>
              <input type="text" name="mail"  class="form-control"/>    
            </div>
            <div class="form-group">
              <label><i class="fa fa-lock" aria-hidden="true"></i> Contraseña</label>
              <input type="password" name="passw" class="form-control"/> 
              <a href="/home/recuperarcontrasena"><h6>Olvide contraseña</h6></a>
            </div>
            <div class="form-group text-center">
             <input type="submit" value="Iniciar Sesión" class="btn btn-primary"/>
           </div>
         </div>
       </div>     
     </form>
   </div>            
 </div>
</div> -->



<div class="row">
  <div class=" col m6 s12">
  <div class="col s12 m7">
    <h2 class="header">Iniciar sesión</h2>
    <div class="card horizontal">
      <div class="card-stacked">
        <div class="card-content">
          <form action="/index/validar" method="POST" enctype="multipart/form-data" class="form-horizontal form-material">
            <input type="hidden" name="ids" value="<?php echo $usr["id"]; ?>">
            <div class="input-field col m12 s12">
                <i class="material-icons prefix">account_circle</i>
                <input id="icon_prefix" type="text" name="mail" class="validate"  required>
                <label for="icon_prefix">Correo:</label>
            </div>

            <div class="input-field col m12 s12">
                <i class="material-icons prefix">lock</i>
                <input id="icon_telephone" type="password" name="passw"  class="validate">
                <label for="icon_telephone">contraseña:</label>
            </div>

            <div class="input-field col m12 s12 text-center">
              <div class="row">
                <div class="col m2 s12"> </div>
                <div class="col m8 s12"><button tyle="submit" id="add_user" class="waves-effect waves-light btn">Iniciar sesión</button></div>
                <div class="col m2 s12"></div>
                
              </div>  
            </div>
          </div>
        </form>
        </div>
        <div class="card-action">
          <!-- <a href="/home/recuperarcontrasena">Olvide contraseña</a> -->
        </div>
      </div>
    </div>
  </div>
  </div>
</div>